[package]
name = "rhap"
version = "0.1.3"
edition = "2021"

[dependencies]
anyhow = "1.0.80"
arrayvec = "0.7.4"
clap = { version = "4.5.1", features = ["derive"] }
crossterm = "0.27.0"
log = "0.4.21"
rand = "0.8.5"
rubato = "0.14.1"
symphonia = { version = "0.5.4", features = ["all-formats", "all-codecs"] }
tokio = { version = "1.36.0", features = ["full"] }
walkdir = "2.5.0"
wasapi = "0.14.0"

[dependencies.ratatui]
version = "0.26.1"
default-features = false
features = ["crossterm", "all-widgets", "macros"]

[dependencies.windows]
version = "0.54.0"
features = [
    "Win32_Foundation",
    "Win32_Security",
    "Win32_System_Com",
    "Win32_System_Threading",
    "Win32_Media_Audio",
    "Devices_Enumeration",
    "Media_Audio",
    "Win32_UI_Shell_PropertiesSystem",
    "Win32_System_Com_StructuredStorage",
    "Win32_Devices_FunctionDiscovery",
    "Win32_Media_KernelStreaming",
    "Win32_Media_Multimedia",
    "Win32_System_Variant",
]

[build]
rustflags = ["-C", "target-cpu=native"]

[profile.release]
opt-level = 3
lto = "fat"
